/**
 * YouTube Transcript Extension
 *
 * Fetches YouTube video transcripts. Port of badlogic/pi-skills/youtube-transcript/transcript.js.
 *
 * Usage:
 *   /youtube-transcript <video-url-or-id>
 *     → Fetches transcript and injects it into the conversation as a user message.
 *       The LLM then has the transcript in context and can summarize, translate,
 *       answer questions, etc.
 *
 *   /youtube-transcript --languages <video-url-or-id>
 *     → Lists available caption languages for the video.
 *
 * Tool: `youtube_transcript` — also callable by the LLM directly.
 *   Returns timestamped transcript text for the agent to process.
 */

import type {
	ExtensionAPI,
	ExtensionCommandContext,
} from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { YoutubeTranscript } from "youtube-transcript-plus";

// -------------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------------

function extractVideoId(input: string): string {
	if (input.includes("youtube.com") || input.includes("youtu.be")) {
		const match = input.match(/(?:v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/);
		if (match) return match[1];
	}
	// Assume it's already a bare video ID
	return input;
}

function formatTimestamp(seconds: number): string {
	const h = Math.floor(seconds / 3600);
	const m = Math.floor((seconds % 3600) / 60);
	const s = Math.floor(seconds % 60);

	if (h > 0) {
		return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
	}
	return `${m}:${s.toString().padStart(2, "0")}`;
}

function formatTranscript(
	segments: { offset: number; text: string }[],
): string {
	return segments
		.map((entry) => `[${formatTimestamp(entry.offset)}] ${entry.text}`)
		.join("\n");
}

// -------------------------------------------------------------------------
// Display helpers
// -------------------------------------------------------------------------

function injectTranscript(
	pi: ExtensionAPI,
	videoId: string,
	segments: { offset: number; text: string }[],
): void {
	const cleanId = extractVideoId(videoId);
	const formatted = formatTranscript(segments);
	const header = `📺 YouTube Transcript: https://www.youtube.com/watch?v=${cleanId} (${segments.length} segments, ${segments.length} lines)`;
	const message = `${header}

${formatted}`;

	pi.sendUserMessage(message);
}

// -------------------------------------------------------------------------
// Entry point
// -------------------------------------------------------------------------

export default function youtubeTranscriptExtension(pi: ExtensionAPI): void {
	// --- Command: /youtube-transcript ---
	// Injects the transcript into the agent as a user message so the LLM can work with it.
	pi.registerCommand("youtube-transcript", {
		description:
			"Fetch the transcript of a YouTube video. " +
			"Usage: /youtube-transcript <video-url-or-id>, " +
			"or /youtube-transcript --languages <video-url-or-id> to list languages",
		getArgumentCompletions: (_prefix: string) => null,
		handler: async (rawArgs, ctx: ExtensionCommandContext) => {
			const args = typeof rawArgs === "string" ? rawArgs.trim() : "";

			if (!args) {
				ctx.ui.notify(
					"Usage:\n" +
						"  /youtube-transcript <video-url-or-id>\n" +
						"  /youtube-transcript --languages <video-url-or-id>\n\n" +
						"Examples:\n" +
						"  /youtube-transcript EBw7gsDPAYQ\n" +
						"  /youtube-transcript https://www.youtube.com/watch?v=dQw4w9WgXcQ\n" +
						"  /youtube-transcript --languages dQw4w9WgXcQ",
					"warning",
				);
				return;
			}

			// Parse --languages flag
			const listOnly = args.startsWith("--languages");
			const videoId = listOnly
				? args.replace(/^--languages\s*/, "").trim()
				: args;

			if (!videoId) {
				ctx.ui.notify("Please provide a video URL or ID.", "warning");
				return;
			}

			ctx.ui.notify(`Fetching YouTube data for ${videoId}...`, "info");

			try {
				if (listOnly) {
					const languages = await YoutubeTranscript.listLanguages(videoId);
					const lines = languages.map(
						(l) =>
							`${l.languageCode} — ${l.languageName}${l.isAutoGenerated ? " (auto)" : ""}`,
					);
					ctx.ui.notify(
						`━━━ Available Languages (${videoId}) ━━━\n\n${lines.join("\n")}`,
						"info",
					);
				} else {
					const transcript = await YoutubeTranscript.fetchTranscript(videoId);
					if (transcript.length === 0) {
						ctx.ui.notify(
							"No transcript entries found for this video.",
							"warning",
						);
						return;
					}
					ctx.ui.notify("Injecting transcript into conversation...", "info");
					injectTranscript(pi, videoId, transcript);
				}
			} catch (error: any) {
				ctx.ui.notify(
					`Error: ${error?.message ?? error ?? "Unknown error"}`,
					"error",
				);
			}
		},
	});

	// --- Tool: youtube_transcript ---
	pi.registerTool({
		name: "youtube_transcript",
		label: "YouTube Transcript",
		description:
			"Fetch the transcript (captions) of a YouTube video by URL or video ID. " +
			"Returns timestamped text segments.",
		promptSnippet: "Fetch YouTube video transcripts",
		promptGuidelines: [
			"Use youtube_transcript when the user asks about the content of a YouTube video, wants a summary, or needs the transcript.",
			"Pass the video URL or just the 11-character video ID.",
		],
		parameters: Type.Object({
			videoId: Type.String({
				description:
					"YouTube video ID (11 characters) or full URL. " +
					"Examples: 'dQw4w9WgXcQ', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'",
			}),
		}),
		async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
			try {
				const transcript = await YoutubeTranscript.fetchTranscript(
					params.videoId,
				);

				if (transcript.length === 0) {
					return {
						content: [
							{
								type: "text",
								text: "No transcript entries found for this video.",
							},
						],
						isError: true,
					};
				}

				const formatted = formatTranscript(transcript);
				const summary = `━━━ YouTube Transcript ━━━\nVideo: ${params.videoId}\nSegments: ${transcript.length}\n\n${formatted}`;

				return {
					content: [{ type: "text", text: summary }],
					details: { segmentCount: transcript.length },
				};
			} catch (error: any) {
				return {
					content: [
						{
							type: "text",
							text: `Error fetching YouTube transcript: ${error?.message ?? error ?? "Unknown error"}`,
						},
					],
					isError: true,
				};
			}
		},
	});
}
